### ISSUE TITLE
ElementParts - port numbers

### ISSUE THREAD

**Issue by MikiDi** [UICrail/SemanticRSM#5]
Hi,

[ElementPart](https://github.com/UICrail/SemanticRSM/wiki/Topology#element-parts)s are defined by 2 `LinearPosition` bounds.  
When one considers an example with a `NetElement` consisting of 3 (or more) `ElementPart`s, at least 4 out of 6 of the `LinearPosition`s involved will be either `0` or `1`. Given that each of the referenced elements already have ports on them with a `portCoordinate` that is either `0` or `1`, it seems a pity that the `Port`s cannot be reused as bounds for ElementParts. After all, in the case of a `LinearElement`, a `Port` can be seen as a specialized `LinearPosition`.

May I also ask to confirm my understanding of what `portNumber` dataType is meant to be exactly? Even without the above question in mind, when considering topological connections of linear elements (more for navigability than connexity I think), it is important to know which side of the element is which ("beginning and end"). May a portNumber be interpreted as a specialized LinearPosition to this end in the case of a linear element?

Thanks,

Michaël Dierick
(collaborating at Infrabel, data-modeling)

**Comment by Airy59** [comment]
Linear **positions** are values over a **continuous interval** [0,1] but, in another version of the model, could become [0, ElementLength]. Using [0,1] was, according to Nicolas Gatez, a choice _partly_ due to the cooperation with British colleagues having a taste for Imperial units - a well-know source of unexpected crashes (see https://en.wikipedia.org/wiki/Mars_Climate_Orbiter). So [0,1] seemed a safer choice. But that's probably not the whole story, it's just that the funny part of the rationale is easier to remember.

_off-topic, but to provide you with more background: the more serious rationale would be that net element lengths are measures (with uncertainties) or calculated (with roundings), and may vary over time, so assigning a particular value to be used for linear element lengths in the sole context of topology sounds bizarre. The intention is to separate geometry from topology. Maybe that's a dogmatic approach, but so far it is rather successful._

On the other hand, **ports** should be designated with distinct ordinals, such as non-negative integers. Maybe not even ordinals, since **port order is not defined** a priori in the model, as it does not need to be defined. I think INFRABEL has a particular _convention_ (such as starting with 1 and counting clockwise along the perimeter of the nonlinear element), which I do not remember precisely.

The fact that linear elements have two ports numbered 0 and 1 that happen to correspond to positions 0.0 and 1.0 is more like a coincidence. This is why I also defined (provocatively) a special type for port numbering. It should disappear from future versions, non-negative integers are fine.

That being said, I hesitated a lot when making such distinctions. Sometimes, compromises need to be made between expressiveness and terseness. So I'll leave this issue open for the time being. Thanks for past and (hopefully) future comments.

**Comment by MikiDi** [comment]
Hi Airy,

Thanks for your reply. In hindsight my original question was formulated in a way that followed my thought process, but could have been more to the point. 

> ports should be designated with distinct ordinals, such as non-negative integers. Maybe not even ordinals, since port order is not defined a priori in the model, as it does not need to be defined.

confirms what we supposed, but leaves us with another question.
Consider the working example appended below. It is a more detailed representation of the illustration in [Topology - purpose](https://github.com/UICrail/SemanticRSM/wiki/Topology#purpose). What I eventually want to get to is the RDF equivalent of the drawing: a `NonlinearElement` consisting of 2 whole `LinearElement`s and 2 half `LinearElement`s. 

How do I express that `0` has to be drawn at `Port` A0 (and not port A1), or `1` has to be drawn below D0, and (and not D1)? These references seem essential to make the next step of defining `LinearElementPart`s and their bounds: the bounds need to be relative to some reference for them to have any value, right?

![semanticrsm_nonlinear_working_example](https://github.com/UICrail/SemanticRSM/assets/9383603/41bc789f-73c1-411e-aff5-f87a0c9a68f9)
```turtle
@base <http://example.org/> .
@prefix srsm: <https://github.com/UICrail/SemanticRSM/> .

<#linear-A>
	a srsm:LinearElement .
	
<#port-A0>
	a srsm:Port ;
	srsm:onElement <#linear-A> .
	
<#port-A1>
	a srsm:Port ;
	srsm:onElement <#linear-A> .


<#port-A1> srsm:connectedToPort <#port-B0> . # symmetric, transitive
<#port-A1> srsm:connectedToPort <#port-C0> . # symmetric, transitive


<#linear-B>
	a srsm:LinearElement .
	
<#port-B0>
	a srsm:Port ;
	srsm:onElement <#linear-B> .
	
<#port-B1>
	a srsm:Port ;
	srsm:onElement <#linear-B> .


<#linear-C>
	a srsm:LinearElement .
	
<#port-C0>
	a srsm:Port ;
	srsm:onElement <#linear-C> .
	
<#port-C1>
	a srsm:Port ;
	srsm:onElement <#linear-C> .


<#port-B1> srsm:connectedToPort <#port-D0> . # symmetric, transitive
<#port-C1> srsm:connectedToPort <#port-D0> . # symmetric, transitive


<#linear-D>
	a srsm:LinearElement .
	
<#port-D0>
	a srsm:Port ;
	srsm:onElement <#linear-D> .
	
<#port-D1>
	a srsm:Port ;
	srsm:onElement <#linear-D> .
```

draw.io source file (note the appended `txt` extension to allow upload here):
[semanticrsm_nonlinear_working_example.drawio.txt](https://github.com/UICrail/SemanticRSM/files/14571116/semanticrsm_nonlinear_working_example.drawio.txt)

**Comment by Airy59** [comment]
Hi Michaël,

Thanks for comments, I’ll look into them tomorrow.

Please use ***@***.***, as amagnien@… is my private address that I sometimes use myself by mistake in this context

Airy

On 12 Mar 2024, at 12:00, Michaël Dierick ***@***.***> wrote:



Hi Airy,

Thanks for your reply. In hindsight my original question was formulated in a way that followed my thought process, but could have been more to the point.

ports should be designated with distinct ordinals, such as non-negative integers. Maybe not even ordinals, since port order is not defined a priori in the model, as it does not need to be defined.

confirms what we supposed, but leaves us with another question.
Consider the working example appended below. It is a more detailed representation of the illustration in Topology - purpose<https://github.com/UICrail/SemanticRSM/wiki/Topology#purpose>. What I eventually want to get to is the RDF equivalent of the drawing: a NonlinearElement consisting of 2 whole LinearElements and 2 half LinearElements.

How do I express that 0 has to be drawn at Port A0 (and not port A1), or 1 has to be drawn below D0, and (and not D1)? These references seem essential to make the next step of defining LinearElementParts and their bounds: the bounds need to be relative to some reference for them to have any value, right?

semanticrsm_nonlinear_working_example.png (view on web)<https://github.com/UICrail/SemanticRSM/assets/9383603/41bc789f-73c1-411e-aff5-f87a0c9a68f9>

@base <http://example.org/> .
@prefix srsm: <https://github.com/UICrail/SemanticRSM/> .

<#linear-A>
        a srsm:LinearElement .

<#port-A0>
        a srsm:Port ;
        srsm:onElement <#linear-A> .

<#port-A1>
        a srsm:Port ;
        srsm:onElement <#linear-A> .


<#port-A1> srsm:connectedToPort <#port-B0> . # symmetric, transitive
<#port-A1> srsm:connectedToPort <#port-C0> . # symmetric, transitive


<#linear-B>
        a srsm:LinearElement .

<#port-B0>
        a srsm:Port ;
        srsm:onElement <#linear-B> .

<#port-B1>
        a srsm:Port ;
        srsm:onElement <#linear-B> .


<#linear-C>
        a srsm:LinearElement .

<#port-C0>
        a srsm:Port ;
        srsm:onElement <#linear-C> .

<#port-C1>
        a srsm:Port ;
        srsm:onElement <#linear-C> .


<#port-B1> srsm:connectedToPort <#port-D0> . # symmetric, transitive
<#port-C1> srsm:connectedToPort <#port-D0> . # symmetric, transitive


<#linear-D>
        a srsm:LinearElement .

<#port-D0>
        a srsm:Port ;
        srsm:onElement <#linear-D> .

<#port-D1>
        a srsm:Port ;
        srsm:onElement <#linear-D> .

draw.io source file (note the appended txt extension to allow upload here):
semanticrsm_nonlinear_working_example.drawio.txt<https://github.com/UICrail/SemanticRSM/files/14571116/semanticrsm_nonlinear_working_example.drawio.txt>

**Comment by MikiDi** [comment]
Only now I notice 
> - orientation (sides)

under the Todo section at the bottom of the [Topology](https://github.com/UICrail/SemanticRSM/wiki/Topology#to-do) wiki page. That covers the contents of this issue I think.

**Comment by Airy59** [comment]
Port Numbers were removed in version 0.1.
